<?php

  /**
   * Register module models for auto-load
   *
   * This file is automatically generated by build_model command
   *
   * @package activeCollab.modules.tasks
   * @subpackage resources
   */
  AngieApplication::useModel(array('public_task_forms', 'task_segments'), 'tasks');