<?php

  /**
   * Register module models for auto-load
   *
   * This file is automatically generated by build_model command
   *
   * @package activeCollab.modules.files
   * @subpackage resources
   */
  AngieApplication::useModel(array('file_versions', 'text_document_versions'), 'files');