<?php

  /**
   * Register module models for auto-load
   *
   * This file is automatically generated by build_model command
   *
   * @package activeCollab.modules.status
   * @subpackage resources
   */
  AngieApplication::useModel(array('status_updates'), 'status');