<?php

  /**
   * Register module models for auto-load
   *
   * This file is automatically generated by build_model command
   *
   * @package activeCollab.modules.system
   * @subpackage resources
   */
  AngieApplication::useModel(array('access_logs', 'currencies', 'day_offs', 'languages', 'api_client_subscriptions', 'users', 'security_logs', 'activity_logs', 'data_filters', 'modification_logs', 'mailing_activity_logs', 'outgoing_messages', 'incoming_mail_attachments', 'incoming_mail_filters', 'incoming_mailboxes', 'incoming_mails', 'homescreen_tabs', 'homescreen_widgets', 'announcements', 'attachments', 'notifications', 'subscriptions', 'comments', 'categories', 'labels', 'subtasks', 'code_snippets', 'payment_gateways', 'payments', 'reminders', 'calendars', 'calendar_events', 'data_sources', 'data_source_mappings', 'companies', 'projects', 'project_roles', 'project_requests', 'project_objects', 'project_templates', 'project_object_templates', 'shared_object_profiles'), 'system');