<?php

  /**
   * Register module models for auto-load
   *
   * This file is automatically generated by build_model command
   *
   * @package activeCollab.modules.documents
   * @subpackage resources
   */
  AngieApplication::useModel(array('documents'), 'documents');